Remove jquery from base_update template
cfpb/consumerfinance.gov pull request #6031
Opened 2020-09-24 17:03 UTC by anselmbradford

## Removals

- Removes jquery from base_update template. 

## How to test this PR

1. This template appears to only be used on:
http://localhost:8000/data-research/consumer-complaints/
https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/offer/test/

2020-09-24 17:23 UTC, wpears requested changes
The `nemo_js` appears to also be used on:
`cfgov/paying_for_college/templates/paying_for_college/disclosure_technote.html`
(though doesn't look like any jquery is actually invoked there)
and there's a reference to the `nemo_js` block on:
`cfgov/legacy/templates/students/helping-borrowers-find-ways-to-stay-afloat/index.html`
but the parent/child relationship is less clear to me on that page.

2020-09-24 17:29 UTC, anselmbradford commented
Thanks @wpears !

> The nemo_js appears to also be used on:
cfgov/paying_for_college/templates/paying_for_college/disclosure_technote.html
(though doesn't look like any jquery is actually invoked there)

Removed in https://github.com/cfpb/consumerfinance.gov/pull/6031/commits/38f9beeea5ce0a91b9482b3fa624db692fa47ae8

> and there's a reference to the nemo_js block on:
cfgov/legacy/templates/students/helping-borrowers-find-ways-to-stay-afloat/index.html
but the parent/child relationship is less clear to me on that page.

This uses a different template and is removed in https://github.com/cfpb/consumerfinance.gov/pull/6030

2020-09-24 18:05 UTC, wpears approved these changes
:+1:

2020-09-25 19:02 UTC, Scotchester approved these changes
One small change that could be thrown in, but otherwise looks good.

2020-09-25 19:02 UTC, Scotchester commented on cfgov/legacy/templates/front/base_update.html
> -</script>
You can also remove the `<ul class="bread meta">` from this template, as nothing that extends this template puts anything in `{% block breadcrumbs %}`.

2020-09-25 20:35 UTC, merged