Remove option to export page metadata as an .xlsx file
cfpb/consumerfinance.gov pull request #6060
Opened 2020-10-01 22:02 UTC by higs4281

The XLSX download option was error-prone for page metadata reports,
possibly because of their size. The XLSX option required that the data be
held in memory before output, whereas the CSV option allows
for a more efficient streaming process.

In any case, not much is lost by removing the option, because the CSV can be
opened in Excel, which then saves the result as an .xlsx file by default.

2020-10-02 14:06 UTC, Scotchester approved these changes
This works. It makes the button slightly ugly, but I don't think I care enough to try to find a fix for that.

I wish there were a built-in way to add/remove options in a report's view code, without overriding the `actions` block. Maybe that's a future contribution we can make upstream.

2020-10-02 14:28 UTC, niqjohnson requested changes
One requested style change to get rid of some extra padding in the button, otherwise it's looking good.

This might be outside the scope of this PR, but is there a not-too-hard way to get rid of the XSLX option globally (even for the standard Wagtail reports)? Our site history report is also huge and gives a 504 error if you try to download the XSLX, though I don't imagine that report will get as many downloads as our custom ones.

2020-10-02 14:28 UTC, niqjohnson commented on cfgov/v1/templates/v1/page_metadata_report.html
> +        <div class="button match-width">
Looks like the `button` class comes with some extra padding that's not needed if there's no dropdown. I think changing that to `actionbutton` should get it looking right (that's the class that's used for buttons like "add an image" in the image manager).

```suggestion
        <div class="actionbutton">
```

2020-10-02 15:52 UTC, willbarton approved these changes
It's a shame that the Excel export action is [implemented entirely in the template](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/templates/wagtailadmin/reports/base_report.html#L18-L28) like this.

2020-10-05 13:29 UTC, higs4281 commented
@niqjohnson It wasn't too hard to remove the XLSX option for site history, but going beyond that does seem out of scope for this PR and runs into the new workflow reports, which I have not explored.

2020-10-05 13:30 UTC, higs4281 commented
> It makes the button slightly ugly ...

@Scotchester Fixed, thanks to @niqjohnson.

2020-10-05 15:22 UTC, niqjohnson approved these changes
The button looks great now, @higs4281, thanks. I'm fine leaving the XSLX option available for the other reports since it's working fine for now.

2020-10-05 15:27 UTC, Scotchester commented
Thank you for being less lazy than me, @niqjohnson 😁

2020-10-05 15:38 UTC, merged