Adding Credit Card agreements tests back to the functional tests.
cfpb/consumerfinance.gov pull request #6929
Opened 2022-03-07 21:15 UTC by baruva

Also adding the data to thee DB needed to pass said tests.
---------

## Additions

- brings back Credit Card Agreements tests back to the front end testing
- Credit Card agreements from Q2 2021 added to test database to ensure we have data that will pass thee test 

## How to test this PR

1.If the Front End test passes this PR has succeeded 

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### Front-end testing

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

2022-03-08 17:59 UTC, Colin-Seifer approved these changes

2022-08-11 20:51 UTC, wpears requested changes
Looks like the db version in the dump is 14, this was likely generated when we were still pulling latest in the k8s setup. Can you regenerate this dump on pg13?

2022-08-19 14:33 UTC, wpears requested changes
All the specs are duplicated between `.js` and `.cy.js` also, I'm somewhat unclear why this is needed or what's actually being introduced. Seems like the core of this is just updating the `test.sql.gz` database but I don't know if this is actually needed since nothing is changing about the structure of the agreements.

2022-08-23 18:44 UTC, baruva commented
> All the specs are duplicated between `.js` and `.cy.js` also, I'm somewhat unclear why this is needed or what's actually being introduced. Seems like the core of this is just updating the `test.sql.gz` database but I don't know if this is actually needed since nothing is changing about the structure of the agreements.

Oh well if I'm not adding back the agreements test as in it was already there then this PR is pointless and can be closed. Maybe we added it in already in another PR and forgot about this one?

2022-08-23 20:46 UTC, closed without merging