Clean up CSS linter issues
cfpb/consumerfinance.gov pull request #7012
Opened 2022-04-15 17:13 UTC by anselmbradford

## Changes

- Remove duplicate selectors.
- Remove `'`, which stylelint doesn't seem to like (we can look at why later).
- Remove typos.
- Remove `css/footer.less` and `css/header.less`

## How to test this PR

1. `yarn build` should pass

2022-04-15 17:20 UTC, anselmbradford commented on cfgov/unprocessed/apps/owning-a-home/js/explore-rates/highcharts-theme.js
> +    fontFamily: '"Avenir Next", Arial, sans-serif',
Removed this for generic font list elsewhere.

2022-04-15 17:21 UTC, anselmbradford commented on cfgov/unprocessed/apps/paying-for-college/css/guides.less
> -    .font-xl {font-size:18px; line-height:26px;}
This was the only duplicate that adjusted the line-height, so I moved it to L9

2022-04-15 17:35 UTC, anselmbradford commented on cfgov/unprocessed/apps/regulations3k/css/reg-navigation.less
> +        &-right {
This appears to have been a typo in https://github.com/cfpb/consumerfinance.gov/commit/e1ddf9d8ec2d4193b6de42fef4337d5cb2507d40 when migrating 
<img width="345" alt="Screen Shot 2022-04-15 at 1 22 43 PM" src="https://user-images.githubusercontent.com/704760/163602682-fc96dd25-9473-47cf-b38e-7be3245c9bb9.png">

2022-04-15 18:39 UTC, wpears requested changes

2022-04-15 18:39 UTC, wpears commented on cfgov/unprocessed/apps/paying-for-college/css/guides.less
> +    // .loans-table {}
```suggestion
```

2022-04-15 18:39 UTC, wpears commented on cfgov/unprocessed/css/organisms/mortgage-performance-trends.less
> +// .o-mp-chart { }
```suggestion
```

2022-04-18 16:40 UTC, wpears approved these changes

2022-04-18 19:05 UTC, merged