Add default series toggle in simple-chart
cfpb/consumerfinance.gov pull request #7056
Opened 2022-05-05 18:30 UTC by brandon-rusk

## Changes

- Added new checkbox in Simple-chart wagtail block to toggle default state of series presentation

## How to test this PR

1. Pull PR
2. `yarn build`
3. `./runserver.sh`
4. Go to http://localhost:8000/admin/pages/4481/edit/
5. Create Simple-Chart block and test new checkbox
6. Publish/preview changes

## Screenshots

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/85513449/166992617-59b2aec1-38b0-4c45-8dc5-475e0fb931de.png">

Unchecked:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/85513449/166993192-cd218e37-5fb8-41d8-949e-0a30c2d34a2b.png">

Checked:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/85513449/166993470-c1646fba-61ca-4e1f-8758-f670ecfbc89d.png">

2022-05-05 20:34 UTC, ielerol reviewed
The wagtail checkbox and helper text lgtm

2022-05-05 21:41 UTC, wpears requested changes
👍 just the hanging comments to trim out

2022-05-05 21:41 UTC, wpears commented on cfgov/templates/wagtailadmin/css/simple-chart-admin.css
> +    /* margin-left: 0; */
```suggestion
```

✂️

2022-05-05 21:41 UTC, wpears commented on cfgov/unprocessed/js/routes/on-demand/simple-chart/simple-chart.js
> +
```suggestion
```
✂️

2022-05-06 02:00 UTC, brandon-rusk commented on cfgov/templates/wagtailadmin/css/simple-chart-admin.css
> +    /* margin-left: 0; */
Woops, thank you!

2022-05-06 12:29 UTC, wpears approved these changes

2022-05-06 12:31 UTC, merged