Dj database url replacement
cfpb/consumerfinance.gov pull request #7120
Opened 2022-06-24 21:22 UTC by baruva

In order to see us up for success in moving our Database related env vars we are changing the old way of getting the database URL which was mostly hard coding to a method that can take in. Currently this causes a failure as PGHOST is being set to a value that is not localhost not the actual host address when we create the pods but that seems to be on purpose and perhaps fixed in the other PR

---

## Additions

- adding env vars for Postgres standard env values like  PGUSER, PGPASSWORD, PGDATABASE, and PGHOST

## Removals

- Had coded values in the DATABASE_URL env var it now depends on the values supplied by the PG env vars now being added

## Changes

-

## How to test this PR

1.

## Screenshots

## Notes and todos

-

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### Front-end testing

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

2022-06-24 21:39 UTC, jslay-excella requested changes
* Need to merge in my Postgres Update branch to bring in the new helper template. 
* Add missing `PGPORT` with default of `5432`. I know we rarely, if ever, define differently, but still should be there.

2022-06-24 21:39 UTC, jslay-excella commented on .github/workflows/functional-tests.yml
>        MAPBOX_ACCESS_TOKEN:  ${{ secrets.MAPBOX_ACCESS_TOKEN }}
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on cfgov/cfgov/settings/base.py
> +        "PORT": "5432",
This should use `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on docker-compose.yml
> +            DATABASE_URL: postgres://cfpb:cfpb@localhost/cfgov
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on docker-entrypoint.sh
> +until psql "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}" -c '\q' >/dev/null 2>&1; do
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on docker-entrypoint.sh
> +  if ! psql "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}" -c 'SELECT COUNT(*) FROM auth_user' >/dev/null 2>&1; then
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on docker-stack.yml
>        DJANGO_ADMIN_USERNAME: admin
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on dump-data.sh
> +    DATABASE_URL=postgres://$PGUSER:$PGPASSWORD@$PGHOST/$PGDATABASE
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on helm/cfgov/templates/deployment.yaml
> +            - name: PGHOST
Please merge in my branch which replaces this with a template helper.

2022-06-24 21:39 UTC, jslay-excella commented on tox.ini
> +    PGUSER PGPASSWORD PGDATABASE PGHOST ES_HOST ES_PORT GITHUB_ACTIONS SKIP_DJANGO_MIGRATIONS TEST_RUNNER
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on tox.ini
> +    PGUSER PGPASSWORD PGDATABASE PGHOST
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on tox.ini
>      DJANGO_SETTINGS_MODULE=cfgov.settings.production
Missing `PGPORT`

2022-06-24 21:39 UTC, jslay-excella commented on tox.ini
> +    DATABASE_URL=postgres://{env:PGUSER:cfpb}:{env:PGPASSWORD:cfpb}@{env:PGHOST:localhost}/{env:PGDATABASE:cfgov}
Missing `PGPORT`

2022-06-24 21:51 UTC, jslay-excella commented
Also, why is a brand new branch starting out with merge commits from 2 months ago?

<img width="442" alt="image" src="https://user-images.githubusercontent.com/59629491/175697574-142c315e-991c-479e-a7a7-da77178bab43.png">

2022-06-27 14:02 UTC, willbarton commented
Just a quick note before I give a more thorough review: we cannot merge these changes without corresponding changes to our deployments, etc, otherwise they'll break.

2022-06-28 21:08 UTC, closed without merging