Disabling the Helm ES chart tests
cfpb/consumerfinance.gov pull request #7201
Opened 2022-08-23 18:39 UTC by baruva

By adding a false value to the elastic search value at the top file we can prevent the 3rd party Elasticsearch chart's test from running. The test for the chart doesn't truly test what we want from our Elasticsearch pod and requires 2 pods to be created to successfully run. Disabling it became necessary  for our custom helm tests to run  as the ES test was failing first causing all other tests to not run. This should now allow the command `helm test <cfgov deployment nam>` to run only the tests we make for our deployments.

Note that this value could be overridden at the `/overrides/` directory in the  values file for any environment should we need to bring it back. 

---

## Additions

- test: false

## Changes

- The ES chart tests will no longer run as a default

## How to test this PR

1. Run the helm-install script to make sure your deployment is updated 2. 
run the command `helm test <your deployment name>`
3. There should be only the smoke test pod running 
## Screenshots

<img width="931" alt="Screen Shot 2022-08-23 at 2 39 00 PM" src="https://user-images.githubusercontent.com/3359736/186237928-9f25a530-8f53-41f1-8248-33a46f7f6178.png">

## Notes and todos

-

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### Front-end testing

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

2022-08-24 14:00 UTC, wpears submitted a review, later dismissed

2022-08-24 15:06 UTC, jslay-excella requested changes

2022-08-24 15:06 UTC, jslay-excella commented on helm/cfgov/values.yaml
> +  test: false
The correct value is `tests`.

See [here](https://github.com/elastic/helm-charts/blob/main/elasticsearch/templates/test/test-elasticsearch-health.yaml#L1).

2022-08-25 16:48 UTC, jslay-excella commented
Closing in favor of #7207

2022-08-25 16:48 UTC, closed without merging