Add fallback for querying document body
cfpb/consumerfinance.gov pull request #7255
Opened 2022-09-23 13:26 UTC by anselmbradford

## Changes

- On the `getComputedStyle` call, add a fallback for querying `document.body` that uses a regular query selector.

## How to test this PR

1. See background in https://[GHE]/CFGOV/platform/issues/4476, we should probably just deploy this and see if it helps, if you'll think it's worthwhile.

2022-09-23 16:50 UTC, wpears requested changes
I think this is actually a Mouseflow (my guess) problem and not a problem with this code. Look like mouseflow does some unguarded `getComputedStyle` calls and is loaded from GTM, which is in the head (meaning it's possible `document.body` doesn't exist yet, etc.)

2022-09-23 18:11 UTC, anselmbradford commented
> I think this is actually a Mouseflow (my guess) problem and not a problem with this code. Look like mouseflow does some unguarded getComputedStyle calls and is loaded from GTM, which is in the head (meaning it's possible document.body doesn't exist yet, etc.)

I'm pretty sure Mouseflow errors in New Relic show the source of the error as a script with "mouseflow" in the file path. This one originates from `common.js`, so is originating from our codebase.

2022-09-23 21:15 UTC, wpears commented
Interesting! Regardless, I don't think this proposed change will actually fix the problem, because if `document.body` is null, `document.querySelector('body')` will be null as well.

I'm curious whether the ordering of scripts in `base.html` is the problem here? There are two scripts below the calls to `jsl`, which COULD mean that if cached scripts are added to the DOM and executed, it could happen before DOMContentLoaded..!

Maybe the solution here is script reordering?

2022-09-26 13:19 UTC, anselmbradford commented
> Interesting! Regardless, I don't think this proposed change will actually fix the problem, because if document.body is null, document.querySelector('body') will be null as well.

Mmm yes, that's probably very true. I was thinking of just testing whether there could be a case where only `document.body` was not implemented, but you're right in that case they almost certainly would both be null.

One thing I just noticed is that this appears to only happen on `https://www.consumerfinance.gov/enforcement/actions/` URLs. What's different about those URLs?

2022-09-27 13:44 UTC, anselmbradford commented
Closing this and adding a note to the issue that this happens to `/enforcement/actions/` URLs and to investigate that further.

2022-09-27 13:44 UTC, closed without merging