ROUT: Update to named imports
cfpb/consumerfinance.gov pull request #7386
Opened 2022-12-02 22:40 UTC by anselmbradford

## Changes

- ROUT: Update to named imports.

## How to test this PR

1. PR checks should pass.

http://localhost:8000/rural-or-underserved-tool/ should be able to search addresses without error. Ping me if you need a CSV file to test.

2022-12-02 22:56 UTC, anselmbradford commented
Coverage failure is N/A. It's because I touched the files.

2022-12-07 14:40 UTC, wpears requested changes

2022-12-07 15:22 UTC, anselmbradford commented on cfgov/unprocessed/apps/rural-or-underserved-tool/js/dom-tools.js
> +export {
`getElData`, `changeElHTML`, `getParentEls` already are (you have to expand the diff lines that are collapsed to see them. Erroneously deleted `getNextEls` though! And missed some required imports 😱

2022-12-07 15:24 UTC, anselmbradford commented on cfgov/unprocessed/apps/rural-or-underserved-tool/js/dom-tools.js
> +export {
https://github.com/cfpb/consumerfinance.gov/pull/7386/commits/597cb49d9258dbd4e17ec6e0102ae0c18561571d

2022-12-07 15:48 UTC, wpears approved these changes

2022-12-07 16:00 UTC, merged