Convert codebase to ESM and remove babel
cfpb/consumerfinance.gov pull request #7412
Opened 2022-12-15 00:04 UTC by anselmbradford

Converts the codebase to use ESM with one caveat:
 - `jest.mock` is not supported anymore and jest provides `jest.unstable_mockModule` (see https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm). I was not able to get the `spyOn` mocks to work in four TDP tests and commented them out for now.  See https://github.com/cfpb/consumerfinance.gov/commit/168644b2e3c662fd94e2955c94a26ac0f77b886d

- https://github.com/cfpb/consumerfinance.gov/pull/7403 needs to go in first for unit tests to pass.

## Removals

- Remove babel.

## Changes

- Convert scripts to ESM modules.
- 

## How to test this PR

1. `yarn build` should pass.
2. `yarn lint` should pass.
3. `yarn jest` should pass (pending FIG PR)

2022-12-20 00:56 UTC, wpears requested changes

2022-12-20 00:56 UTC, wpears commented
This is soooooooooooo rad! Good job on all the work that went into this!

2022-12-21 15:26 UTC, anselmbradford commented on cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-census.js
> +import jsonpPModule from 'jsonp-p';
I get `Uncaught (in promise) TypeError: (0 , an.default) is not a function`

2022-12-21 15:27 UTC, anselmbradford commented on cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-tiger.js
> +import jsonpPModule from 'jsonp-p';
I get `Uncaught (in promise) TypeError: (0 , an.default) is not a function`

This whole 6-year old dependency should likely be stripped out and approached a different way.

2022-12-21 16:24 UTC, anselmbradford commented on .eslintrc.cjs
> +    sourceType: 'module',
For now it does unfortunately. The underlying dependency does not yet treat this as ESM. The error is :

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /[user project path]/consumerfinance.gov/.eslintrc.js from /[user project path]/consumerfinance.gov/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of .eslintrc.js in /[user project path]/consumerfinance.gov/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
```

2022-12-21 22:28 UTC, wpears commented on cfgov/unprocessed/apps/rural-or-underserved-tool/js/call-tiger.js
> +import jsonpPModule from 'jsonp-p';
Agreed, I might actually put that in as separate PR realllll quick.

2022-12-22 17:54 UTC, wpears approved these changes

2022-12-22 17:54 UTC, merged