Add prepaid agreements script
cfpb/consumerfinance.gov pull request #7702
Opened 2023-05-02 18:45 UTC by anselmbradford

Not totally sure how this was working before, but the expandables aren't initialized. This PR adds a script to initialize them.

## Additions

- Add prepaid script to initialize expandable group.

## How to test this PR

1. Compare filter expandables in http://localhost:8000/data-research/prepaid-accounts/search-agreements/ vs https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/

## Screenshots

Before:
<img width="530" alt="Screen Shot 2023-05-02 at 2 42 50 PM" src="https://user-images.githubusercontent.com/704760/235757152-360601e1-8659-455d-b825-62fc79802202.png">

After:
<img width="535" alt="Screen Shot 2023-05-02 at 2 42 33 PM" src="https://user-images.githubusercontent.com/704760/235757183-1819e73a-621d-48b3-8453-8ce2eeaa9bd3.png">

2023-05-02 21:20 UTC, wpears requested changes
Let's make default these to open on load to match the current experience

2023-05-02 22:22 UTC, anselmbradford commented
> Let's make default these to open on load to match the current experience

The current experience is broken. It's showing the no-js state (where expandables expand open by default), because the expandables are not initialized.

2023-05-02 22:25 UTC, anselmbradford commented
Not sure when this broke, but you can see the closed appearance in wayback machine:

<img width="1061" alt="Screen Shot 2023-05-02 at 6 24 38 PM" src="https://user-images.githubusercontent.com/704760/235798722-e99e4382-636f-4a88-9e25-9d7e3937d65a.png">

2023-05-03 12:41 UTC, wpears approved these changes

2023-05-03 14:28 UTC, merged