Fix broken notes in repository documentation
cfpb/consumerfinance.gov pull request #7930
Opened 2023-08-18 19:31 UTC by chosak

Commit 2aac096a178ef8b34c13db53354605cead24ef07 added Markdown files to Prettier, which prohibits leading spaces. This breaks the use of the `!!! note` syntax [which requires that note text be indented](https://python-markdown.github.io/extensions/admonition/#syntax).

This PR also fixes notes in a Markdown file that isn't part of the documentation - CONTRIBUTING.md - as per the guidance [here](https://github.com/orgs/community/discussions/16925#discussioncomment-6682796). Note that this may not show up properly on the PR preview but you can see it working on the branch [here](https://github.com/cfpb/consumerfinance.gov/blob/fix/docs-notes/CONTRIBUTING.md#outputting-browser-support-metrics).

Finally, this PR excludes Markdown files from Prettier, both as part of the frontend lint script and in VSCode. Another way of doing this would be to exclude docs/ and explicitly CONTRIBUTING.md in the .prettierignore file but that seemed overly complex for little benefit.

## Screenshots

Before|After
-|-
<img width="749" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/1d5213cb-3152-450f-aff5-03abee7639c7">|<img width="742" alt="image" src="https://github.com/cfpb/consumerfinance.gov/assets/654645/0284b5f3-fa1a-47ea-987d-0351fbeb1087">

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)

2023-08-18 20:45 UTC, anselmbradford requested changes
Prettier supports this :) We just need a space between the admonition and its content. So instead of

```
!!! note "Don't forget the migrations!"
   Adding or changing fields on either Python class will always require a new
   [Django schema migration](https://docs.djangoproject.com/en/1.11/topics/migrations/);
   additionally, changing field names or types
   on an existing block will require a
   [Django data migration](https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations).
   See the guide on
   [creating migrations for StreamField blocks](#creating-migrations-for-streamfield-blocks)
   for more details.
```
 
 Have
 
 ```
 !!! note "Don't forget the migrations!"

    Adding or changing fields on either Python class will always require a new
    [Django schema migration](https://docs.djangoproject.com/en/1.11/topics/migrations/);
    additionally, changing field names or types
    on an existing block will require a
    [Django data migration](https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations).
    See the guide on
    [creating migrations for StreamField blocks](#creating-migrations-for-streamfield-blocks)
    for more details.
 ```
 
Commit 2aac096a178ef8b34c13db53354605cead24ef07 stripped these because they were only one indent, not two.

2023-10-12 12:47 UTC, anselmbradford commented
@chosak Just looking at this one again. It looks like all that would be needed is to add a newline after the `!!! note` lines and revert the prettier changes. Are you good with that?

2023-10-13 16:34 UTC, chosak commented
Thank you @anselmbradford, I think this is ready for re-review.

2023-10-13 16:35 UTC, anselmbradford approved these changes

2023-10-13 17:22 UTC, merged