Replace jQuery in "Before You Claim"
cfpb/consumerfinance.gov pull request #8321
Opened 2024-04-15 14:05 UTC by mistergone

This PR replaces jquery functions and methods with "vanilla" JavaScript so we no longer rely on jQuery in this app.

I attempted to replace jQuery without changing any lines of the existing code, but I did have to change the reference to a few event handlers just for ease. The existing functional tests are passing.

## Additions
- Add `dollar-sign.js` which replaces relevant jQuery methods.

## Changes
- Change a few event handlers to use `Query.on()` 

## How to test this PR
1. Check the functional tests in cypress
2. Visually check [the app](http://localhost:8000/consumer-tools/retirement/before-you-claim/) to make sure it matches the [production apa](http://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/)

## Checklist
- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [x] Future todos are captured in comments and/or tickets
- [x] Project documentation has been updated, potentially one or more of:

### Front-end testing

*This app should function exactly as it did before.*

2024-04-16 12:12 UTC, anselmbradford commented on cfgov/unprocessed/apps/retirement/js/views/graph-view.js
> +  $('#claim-canvas').on('click', '[data-bar_age]', function () {
What even is `[data-bar_age]` doing in this call? In the original jquery `on` method docs https://api.jquery.com/on/, it shows the second argument as being passed to the `event.data` object, but this object isn't referenced in the event handler function here, and in fact, the attribute name is looked up independent of the value of this argument. 

Could this whole thing be re-written to something like this?

```js
const claimCanvasDom = document.querySelector('#claim-canvas');
claimCanvasDom.addEventListener('click', function() {
   const age = claimCanvasDom.getAttribute('data-bar_age');
   moveIndicatorToAge(age);
});
```

2024-04-16 12:16 UTC, anselmbradford commented on cfgov/unprocessed/apps/retirement/js/views/graph-view.js
>    });
Similar to above, could this be re-written to something like:

```js
const claimCanvasDom = document.querySelector('#claim-canvas');
claimCanvasDom.addEventListener('change', handleAgeIndicator);
claimCanvasDom.addEventListener('input', handleAgeIndicator);

function handleAgeIndicator() {
   const indicatorValue = claimCanvasDom.value();
   setAgeWithIndicator(indicatorValue);
}
```

2024-04-16 12:24 UTC, anselmbradford commented
Whoops, gave some suggestions and then realized I mis-read the jquery code for https://api.jquery.com/on/ and had the `selector` and `data` arguments swapped in my head. Deleted suggestions.

2024-10-10 15:55 UTC, mistergone commented
It looks like whatever wasn't working in cypress before is working now(?). @wpears - Do you mind looking over this for me?

2024-10-10 16:16 UTC, wpears commented
I'm a bit queasy about having two jquery replacements, this one and the one in the `disclosures` app. Is it possible to move this version of dollar-sign to `cfgov/unprocessed/js/modules/util` and use it in both retirement and disclosures?

2024-10-16 14:36 UTC, mistergone commented
@wpears - I had some problems with my local environment, but I figured them out, successfully moved the `dollar-sign.js` file to the `util` folder, and now the tests all pass. Hooray!

2024-10-16 16:07 UTC, wpears requested changes
~~Getting the following in before you claim:~~
<img width="684" alt="Screenshot 2024-10-16 at 9 06 57 AM" src="https://github.com/user-attachments/assets/48e9e6f1-ad2c-4d0a-8c1a-6b09188fe14b">

~~and the age adjustment slider isn't operating.~~

**UPDATE** Fixed in [8a3bee2](https://github.com/cfpb/consumerfinance.gov/pull/8321/commits/8a3bee22ebd0ec919307d889840763c46074028e)

2024-10-17 16:44 UTC, mistergone commented
> ~Getting the following in before you claim:~ <img alt="Screenshot 2024-10-16 at 9 06 57 AM" width="684" src="https://private-user-images.githubusercontent.com/1558033/377138257-48e9e6f1-ad2c-4d0a-8c1a-6b09188fe14b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODM3MDIsIm5iZiI6MTcyOTE4MzQwMiwicGF0aCI6Ii8xNTU4MDMzLzM3NzEzODI1Ny00OGU5ZTZmMS1hZDJjLTRkMGEtOGMxYS02YjA5MTg4ZmUxNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMTY0MzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBjNzJlNTM1NWIyMzhlNzUzYTk0ZjEwMjU4YzIxMjRlYTQ1MDI2MmEyNjA5ZTJiMTJlNjc4OGIzZWVkNDRmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XNIRBttuVh4Unim3Q-ie0IhDhCiCE1YACI3Tt-Fl9tE">
> 
> **UPDATE** Fixed in [8a3bee2](https://github.com/cfpb/consumerfinance.gov/pull/8321/commits/8a3bee22ebd0ec919307d889840763c46074028e)
> 
> But the age adjustment slider isn't operating

I found an incorrect selector that was breaking the slider, and it should be okay now. It was probably a bug from when I was originally writing this PR. We don't have any current functional tests for the slider itself. 😦

2024-10-17 18:46 UTC, wpears approved these changes
:cool:

2024-10-22 16:47 UTC, merged