Add translation links to the hero
cfpb/consumerfinance.gov pull request #8340
Opened 2024-04-22 14:47 UTC by wpears

Currently, pages with heroes don't get `translation-links` like pages with item introductions or text-introductions. This PR changes that, rendering these links if they exist (english versions of translated pages set in the wagtail config).

## Testing
- Get a recent dump
- Visit https://www.consumerfinance.gov/consumer-tools/ and notice no links
- Compare with http://localhost:8000/consumer-tools/ and notice the links
- Pages with heroes (or jumbo heroes) and no linked translations (like the homepage at http://localhost:8000) should not render any new markup

2024-04-22 14:57 UTC, chosak commented
@wpears for posterity (and to make it easier to review without doing a local setup) could you paste a before-and-after screenshot here to see what this looks like on hero pages?

2024-04-22 14:59 UTC, chosak commented on cfgov/v1/jinja2/v1/includes/molecules/hero.html
> +{% set t_links = translation_links.render(None, 'block__flush-bottom') %}
```suggestion
{% set t_links = translation_links.render(modifier_classes='block__flush-bottom') %}
```

2024-04-22 19:05 UTC, wpears commented
Before:
<img width="1408" alt="Screenshot 2024-04-22 at 3 05 07 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/1558033/dff63775-e516-472e-96c7-b2a53cdf0415">

After:
<img width="1354" alt="Screenshot 2024-04-22 at 3 05 16 PM" src="https://github.com/cfpb/consumerfinance.gov/assets/1558033/703f08a5-6c65-4be4-9ab6-75ffc260a1ca">

2024-04-22 19:06 UTC, wpears commented
Oh that just made me notice a bug! The sidebar is wrong, one moment

2024-04-26 18:29 UTC, anselmbradford requested changes

2024-04-26 18:29 UTC, anselmbradford commented on cfgov/v1/jinja2/v1/landing-page/index.html
> +    {% if has_hero %}
We could use namespaces to omit the temp variable. I would also swap the conditional around so its not checking a negation first:

```
…
{% set has_hero = namespace(found=false) %}
    {% for block in page.header -%}
        {% if block.block_type == 'hero' %}
            {% set has_hero.found = true %}
        {% else %}
            {{ render_block.render(block, loop.index) }}
        {% endif %}
    {%- endfor %}
    {% if has_hero.found %}
 …
```

2024-04-26 18:34 UTC, anselmbradford requested changes

2024-04-26 18:34 UTC, anselmbradford commented on cfgov/v1/jinja2/v1/landing-page/index.html
> +      {% set t_links = translation_links.render(modifier_classes='block__flush-top') %}
When you rebase with `main`, update `block__flush-top` to `block--flush-top`

2024-04-26 19:07 UTC, anselmbradford commented
One thing you might double-check is any landing page that doesn't have a hero. I'm not sure which page this might be offhand.

2024-04-26 19:30 UTC, merged