TCCP: Update content
cfpb/consumerfinance.gov pull request #8658
Opened 2024-11-26 17:51 UTC by niqjohnson

Update TCCP with cleared content

---

## Changes

- Content on landing and about pages

## How to test this PR

1. Check `/consumer-tools/credit-cards/explore-cards/` and `/consumer-tools/credit-cards/explore-cards/about/` to make sure the updated content looks OK.

## Notes and todos

- We discovered a hero bug that vertically centers the hero text when the text is short enough to not run the full width of the container. We're working on a fix for that separately in the Design System, so you can ignore the misaligned hero for now.

## Checklist

- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [x] Future todos are captured in comments and/or tickets

2024-11-26 19:06 UTC, chosak approved these changes
Looks great! Been too long since I loaded the TCCP landing page locally.

One minor question, is it expected that the date format will use abbreviated months here?
<img width="675" alt="image" src="https://github.com/user-attachments/assets/b1a89ae0-c24d-4e28-9662-75097c5c2b38">

2024-11-26 19:54 UTC, chosak requested changes

2024-11-26 19:54 UTC, chosak commented on cfgov/tccp/jinja2/tccp/landing_page.html
> +                This tool is updated every six months and is currently based on data from {{ date(stats.first_report_date) }}. Advertised purchase APRs change over time. Check rates before applying a
We should handle the case when there are no cards in the database for whatever reason.

```suggestion
                This tool is updated every six months
                {%- if stats.first_report_date %}
                and is currently based on data from {{ date(stats.first_report_date) }}
                {%- endif %}.
                Advertised purchase APRs change over time. Check rates before applying and
```

2024-11-26 20:26 UTC, niqjohnson commented
@chosak, good catch about handling an edge case with no cards, that's fixed in 432b10d. The abbreviated month is a little weird in that I'm pretty sure our style guide for dates follows AP style, so it should be "June 30, 2024" for months with short names but "Dec. 31, 2024" for months with longer names. Since we're using the same `date` macro for the data publication date everywhere in TCCP, including where it comes up in text in spots on the other pages, I'm inclined to leave it like that for now and look at fixing it globally in a subsequent PR later (with apologies to @higs4281 for breaking AP style for now).

2024-11-27 00:26 UTC, chosak approved these changes

2024-12-02 15:54 UTC, merged