[WIP] TCCP: ITAP Changes
cfpb/consumerfinance.gov pull request #8675
Opened 2024-12-06 18:45 UTC by mistergone

- Remove fade styling from `u-show-more` and update button behavior
- Remove `tabindex` from tooltip elements
- Remove link styling from card list elements

---

## Additions

-

## Removals

-

## Changes

-

## How to test this PR

1.

## Screenshots

| Before | After  |
| ------ | ------ |
|        |        |

## Notes and todos

-

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### Front-end testing

#### Browser testing

Check the current browser support cutoff list](https://cfpb.github.io/consumerfinance.gov/browser-support#current-browser-support-metrics) for browsers that are advisable
to prioritize for testing.

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

2024-12-16 22:39 UTC, wpears requested changes
Looks good and functions as described, just a few small things

2024-12-16 22:39 UTC, wpears commented on cfgov/unprocessed/apps/tccp/js/index.js
> +  });
I think this can just be 
```suggestion
  nextResult.querySelector('[tabindex="-1"]').setAttribute('tabIndex', '0');
```

2024-12-16 22:39 UTC, wpears commented on cfgov/unprocessed/apps/tccp/css/main.scss
> +//      border-bottom: 1px solid $link-underline-hover;
Looks like we can remove this whole selector

2024-12-17 17:05 UTC, mistergone commented
@wpears - I accidentally resolved your request, but I uploaded the new code, so that should resolve it!

2024-12-17 17:07 UTC, wpears approved these changes

2024-12-17 17:54 UTC, merged

2024-12-17 18:00 UTC, niqjohnson requested changes